dbpn:
    scale: 4
    mode: 'dbpn'
    num_channels: 3
    base_filter: 64
    feat: 256
    num_stages: 7

batch_shape: [16, 3, 32, 32]
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [500]
    decay_rate: 0.1
