---
drsr_v2:
  weights: [1, 10, 1.0e-5]
  # mean_shift: [0, 0, 0]
  level: 1
  arch: 'crdb'
  auto_shift: true
  noise_config:
    max: 75.0
    scale: 1.0
    offset: 0.0
    penalty: 0.7
    layers: 8
    crf: "../Data/crf.npz"
    valid: false
  channel: 3
  scale: 4

patch_size: 128
batch: 16
lr: 1.0e-4
lr_decay:
  method: multistep
  decay_step: [150000]
  decay_rate: 0.1
